name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run:
        rustup default nightly-x86_64-pc-windows-gnu && cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
